__all__ = ["ApplicationError", "UsecaseError", "EntityAlreadyExistsError"]


class ApplicationError(Exception): ...


class UsecaseError(ApplicationError): ...


class EntityAlreadyExistsError(ApplicationError): ...


class InconsistentDataError(ApplicationError): ...
