from .composite import AnyOf, AllOf
from .permissions import (
    CanDeleteProject,
    CanManageRole,
    CanManageSelf,
    CanManageProjectContent,
    CanUpdateProject,
    RoleManagementContext,
    UserManagementContext,
    ProjectManagmentContext,
    ProjectContentManagmentContext,
    ProjectGroupManagmentContext,
    CanDeleteAccessList,
    AccessListManagmentContext,
    CanAssignAccessList,
    CanChangePrivateness,
    CanManageProjectGroup,
    CanManageProjectTask,
    CanCompleteProjectTask,
    CanCancelProjectTask,
    CanAddGroupParticipant,
    ProjectGroupParticipantManagmentContext,
    CanAssignProjectTaskTeam,
    ProjectTaskTeamAssignmentContext,
    ProjectTaskCompleteContext,
    ProjectTaskCancelContext,
)
from .authorize import authorize
