from fastapi import APIRouter
from .create_project import create_create_project_router
from .list_projects import create_list_projects_router
from .update_project import create_update_project_router
from .delete_project import create_delete_project_router
from .grant_owner import create_grant_owner_router
from .add_member import create_add_member_router
from .remove_member import create_remove_member_router
from .list_members import create_list_members_router
from .set_role import create_set_role_router
from .add_directory import create_add_directory_router
from .add_document import create_add_document_router
from .list_directory_content import create_list_directory_content_router
from .delete_document import create_delete_document_router
from .delete_directory import create_delete_directory_router
from .access_content import create_content_ticket_router
from .get_document_content import create_get_document_content_router
from .add_access_list import create_add_acl_router
from .list_access_lists import create_list_acls_router
from .delete_access_list import create_delete_acl_router
from .assign_directory_access_list import create_assign_directory_acl_router
from .assign_document_access_list import create_assign_document_acl_router
from .set_project_access import create_set_project_access_router
from .releases import create_project_release_router

projects_router = APIRouter(prefix="/project", tags=["project"])
projects_router.include_router(create_create_project_router())
projects_router.include_router(create_list_projects_router())
projects_router.include_router(create_update_project_router())
projects_router.include_router(create_delete_project_router())
projects_router.include_router(create_grant_owner_router())
projects_router.include_router(create_add_member_router())
projects_router.include_router(create_list_members_router())
projects_router.include_router(create_list_acls_router())
projects_router.include_router(create_set_project_access_router())
projects_router.include_router(create_remove_member_router())
projects_router.include_router(create_set_role_router())
projects_router.include_router(create_add_acl_router())
projects_router.include_router(create_add_directory_router())
projects_router.include_router(create_add_document_router())
projects_router.include_router(create_list_directory_content_router())
projects_router.include_router(create_delete_document_router())
projects_router.include_router(create_delete_directory_router())
projects_router.include_router(create_delete_acl_router())
projects_router.include_router(create_assign_directory_acl_router())
projects_router.include_router(create_assign_document_acl_router())
projects_router.include_router(create_content_ticket_router())
projects_router.include_router(create_get_document_content_router())
projects_router.include_router(create_list_acls_router())
projects_router.include_router(create_project_release_router())
