"""Add proj_membership user idx

Revision ID: 745a44a3c2d6
Revises: ff86c2de0599
Create Date: 2026-02-17 14:08:43.609508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745a44a3c2d6'
down_revision: Union[str, Sequence[str], None] = 'ff86c2de0599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_memberships_user_id'), 'project_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_memberships_user_id'), table_name='project_memberships')
    # ### end Alembic commands ###
