"""Add task table for outbox

Revision ID: 83891064ccbe
Revises: 745a44a3c2d6
Create Date: 2026-02-19 18:50:36.351073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83891064ccbe'
down_revision: Union[str, Sequence[str], None] = '745a44a3c2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id_', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'SENT', 'FAILED', 'CANCELED', name='status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resend_time', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index('ix_tasks_created_resend_time', 'tasks', ['resend_time'], unique=False, postgresql_where=sa.text("status = 'CREATED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_created_resend_time', table_name='tasks', postgresql_where=sa.text("status = 'CREATED'"))
    op.drop_table('tasks')
    # ### end Alembic commands ###
