"""Add version project

Revision ID: 3ef0732e19fa
Revises: 5e937dda0848
Create Date: 2026-02-09 15:59:11.576710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef0732e19fa'
down_revision: Union[str, Sequence[str], None] = '5e937dda0848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('version', sa.Integer(), nullable=False, server_default="1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'version')
    op.drop_column('projects', 'updated_at')
    # ### end Alembic commands ###
