"""add feature to pin acl to project unit

Revision ID: 63bfd8b59e08
Revises: b467a4e99cee
Create Date: 2026-03-24 14:58:31.106252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63bfd8b59e08'
down_revision: Union[str, Sequence[str], None] = 'b467a4e99cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_unit_nodes', sa.Column('access_list_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'project_unit_nodes', 'access_lists', ['access_list_id'], ['id_'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_unit_nodes', type_='foreignkey')
    op.drop_column('project_unit_nodes', 'access_list_id')
    # ### end Alembic commands ###
