"""empty message

Revision ID: ff86c2de0599
Revises: 5ae510ea5c0c
Create Date: 2026-02-17 14:07:04.516281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff86c2de0599'
down_revision: Union[str, Sequence[str], None] = '5ae510ea5c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_root_unique_name'), table_name='project_unit_nodes', postgresql_where='(parent_id IS NULL)')
    op.create_index('ix_project_single_root', 'project_unit_nodes', ['project_id'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_single_root', table_name='project_unit_nodes', postgresql_where=sa.text('parent_id IS NULL'))
    op.create_index(op.f('ix_node_root_unique_name'), 'project_unit_nodes', ['name', 'project_id'], unique=True, postgresql_where='(parent_id IS NULL)')
    # ### end Alembic commands ###
