"""include private field for project

Revision ID: 7546d0cfa96c
Revises: 63bfd8b59e08
Create Date: 2026-03-29 16:27:16.809814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7546d0cfa96c"
down_revision: Union[str, Sequence[str], None] = "63bfd8b59e08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("is_private", sa.Boolean(), nullable=False, server_default="FALSE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "is_private")
    # ### end Alembic commands ###
