"""add polymorph type

Revision ID: b467a4e99cee
Revises: 010bb3d1a777
Create Date: 2026-03-20 19:02:31.831410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b467a4e99cee'
down_revision: Union[str, Sequence[str], None] = '010bb3d1a777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_rule_targets', sa.Column('type_', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_rule_targets', 'type_')
    # ### end Alembic commands ###
