"""Add acls

Revision ID: 010bb3d1a777
Revises: 785411fbf1d8
Create Date: 2026-03-20 11:56:23.563073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "010bb3d1a777"
down_revision: Union[str, Sequence[str], None] = "785411fbf1d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_rule_targets",
        sa.Column("id_", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_table(
        "access_lists",
        sa.Column("id_", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["owner"], ["users.id_"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_"),
        sa.UniqueConstraint("name", "project_id"),
    )
    op.create_table(
        "access_rule_role_targets",
        sa.Column(
            "role",
            sa.Enum("OWNER", "LEAD", "MEMBER", name="targetrole"),
            nullable=False,
        ),
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_"], ["access_rule_targets.id_"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_"),
        sa.UniqueConstraint("role"),
    )
    op.create_table(
        "access_rule_user_targets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_"], ["access_rule_targets.id_"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "access_rules",
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("READ", "WRITE", "EXECUTE", name="projectunitaction"),
            nullable=False,
        ),
        sa.Column("access_list_id", sa.Uuid(), nullable=False),
        sa.Column("is_allow", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_list_id"], ["access_lists.id_"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["access_rule_targets.id_"],
        ),
        sa.PrimaryKeyConstraint("target_id", "action", "access_list_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("access_rules")
    op.drop_table("access_rule_user_targets")
    op.drop_table("access_rule_role_targets")
    op.drop_index("ix_project_unique_acl", table_name="access_lists")
    op.drop_table("access_lists")
    op.drop_table("access_rule_targets")
    # ### end Alembic commands ###
