"""Fill projects with meat

Revision ID: 5ae510ea5c0c
Revises: 3ef0732e19fa
Create Date: 2026-02-11 19:28:51.680608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ae510ea5c0c'
down_revision: Union[str, Sequence[str], None] = '3ef0732e19fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_unit_nodes',
    sa.Column('id_', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit_type', sa.Enum('DIRECTORY', 'DOCUMENT', name='unit_type'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id_'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['project_unit_nodes.id_'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('name', 'parent_id', 'project_id')
    )
    op.create_index('ix_node_root_unique_name', 'project_unit_nodes', ['name', 'project_id'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    op.create_index(op.f('ix_project_unit_nodes_parent_id'), 'project_unit_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_project_unit_nodes_project_id'), 'project_unit_nodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_unit_nodes_unit_type'), 'project_unit_nodes', ['unit_type'], unique=False)
    op.drop_constraint(op.f('project_memberships_project_id_fkey'), 'project_memberships', type_='foreignkey')
    op.drop_constraint(op.f('project_memberships_user_id_fkey'), 'project_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'project_memberships', 'projects', ['project_id'], ['id_'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_memberships', 'users', ['user_id'], ['id_'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_memberships', type_='foreignkey')
    op.drop_constraint(None, 'project_memberships', type_='foreignkey')
    op.create_foreign_key(op.f('project_memberships_user_id_fkey'), 'project_memberships', 'users', ['user_id'], ['id_'])
    op.create_foreign_key(op.f('project_memberships_project_id_fkey'), 'project_memberships', 'projects', ['project_id'], ['id_'])
    op.drop_index(op.f('ix_project_unit_nodes_unit_type'), table_name='project_unit_nodes')
    op.drop_index(op.f('ix_project_unit_nodes_project_id'), table_name='project_unit_nodes')
    op.drop_index(op.f('ix_project_unit_nodes_parent_id'), table_name='project_unit_nodes')
    op.drop_index('ix_node_root_unique_name', table_name='project_unit_nodes', postgresql_where=sa.text('parent_id IS NULL'))
    op.drop_table('project_unit_nodes')
    # ### end Alembic commands ###
