"""Add lead project role

Revision ID: 5e937dda0848
Revises: 8b60a5dbb18b
Create Date: 2026-02-04 14:13:58.259959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e937dda0848'
down_revision: Union[str, Sequence[str], None] = '8b60a5dbb18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. создаём новый enum
    op.execute("""
        CREATE TYPE projectrole_new AS ENUM (
            'OWNER',
            'LEAD',
            'MEMBER'
        )
    """)

    # 2. переводим колонку через TEXT
    op.execute("""
        ALTER TABLE project_memberships
        ALTER COLUMN role TYPE TEXT
    """)

    # 3. маппим старые значения
    op.execute("""
        UPDATE project_memberships
        SET role = UPPER(role)
    """)

    # 4. меняем тип на новый enum
    op.execute("""
        ALTER TABLE project_memberships
        ALTER COLUMN role TYPE projectrole_new
        USING role::projectrole_new
    """)

    # 5. удаляем старый enum
    op.execute("DROP TYPE projectrole")

    # 6. переименовываем новый
    op.execute("ALTER TYPE projectrole_new RENAME TO projectrole")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
