"""Add user/project m2m2

Revision ID: 8b60a5dbb18b
Revises: 46a68cd2b1c1
Create Date: 2025-11-18 10:58:09.050419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b60a5dbb18b'
down_revision: Union[str, Sequence[str], None] = '46a68cd2b1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_memberships',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='projectrole'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_memberships')
    # ### end Alembic commands ###
